### ISSUE TITLE
The link to ggplot2 extensions gallery leads to an explicit website

### ISSUE THREAD

**Issue by psyguy** [gadenbuie/gentle-ggplot2#6]
Hi, thanks for teh great slides!

In the slides (e.g. [here](https://pkg.garrickadenbuie.com/gentle-ggplot2/#157)) you have written the link `ggplot2-exts[.]org`, which leads to a terribly explicit website. It appears in [these locations](https://github.com/gadenbuie/gentle-ggplot2/search?q=ggplot2-exts) in the repo.

Maybe change it to https://exts.ggplot2.tidyverse.org/gallery/?

**Comment by gadenbuie** [comment]
Oh no! 😱 🙈 I knew about the unfortunate change in content at that link but didn't realize I had old material that linked to it. I'll change that ASAP and thanks for alerting me!
